---
- name: Download a wordpress theme
  copy:
    src: files/wptheme.zip
    dest: /tmp/wptheme.zip
    force: no

- name: Install the theme
  shell: sudo -u www-data unzip -o -q /tmp/wptheme.zip -d /var/www/html/wp-content/themes
  args:
    warn: no

- name: Install wordpress
  command: >
    wp core install --path=/var/www/html
    --url="http://{{ groups['balancers'][0] }}"
    --title='OpenStack Interop Challenge'
    --admin_user=wpuser
    --admin_password="{{ db_pass }}"
    --admin_email='interop@openstack.org'
    --allow-root

- name: Make an initial request, so that later switch-theme hooks work.
  shell: >
    sudo -u www-data wp --path=/var/www/html
    cron test

- name: Activate wordpress theme
  command: >
    wp --path=/var/www/html theme activate superuser --allow-root

- name: Install required plugins
  shell: >
    sudo -u www-data wp --path=/var/www/html plugin install {{ item }} && sleep 2
  with_items:
    - advanced-custom-fields
    - cforms2
    - co-authors-plus
    - disable-comments
    - pmzez-page-loader
    - responsive-lightbox
  args:
    warn: no

- name: Activate required plugins
  shell: >
    sudo -u www-data wp --path=/var/www/html plugin activate {{ item }} && sleep 2
  with_items:
    - advanced-custom-fields
    - cforms2
    - co-authors-plus
    - disable-comments
    - pmzez-page-loader
    - responsive-lightbox
  args:
    warn: no

- name: Activate required plugins II
  shell: >
    sudo -u www-data wp --path=/var/www/html plugin install {{ item }} --activate && sleep 2
  with_items:
    - /var/www/html/wp-content/themes/superuser/src/plugins/pbd-ajax-load-posts.zip
    - /var/www/html/wp-content/themes/superuser/src/plugins/share-links.zip\

- name: Download wordpress importer plugin
  get_url:
    url: "{{ app_env.wp_importer | default('http://downloads.wordpress.org/plugin/wordpress-importer.0.6.3.zip') }}"
    dest: "/tmp/wordpress-importer.zip"
    force: "yes"

- name: Install wordpress importer plugin
  command: >
    sudo -u www-data wp --path=/var/www/html plugin install /tmp/wordpress-importer.zip --activate
  args:
    warn: "no"

- name: Create temporary post directory
  file:
    path: /tmp/posts
    state: directory
    mode: "u=rwx,g=rwx,o=rx"

- name: Unpack the posts
  unarchive:
    src: files/wpposts.zip
    dest: /tmp/posts
    remote_src: no

- name: Wait for the posts to be unpacked
  wait_for:
    path: /tmp/posts
    state: present

- name: Import wordpress posts
  command: >
    wp --path=/var/www/html import /tmp/posts/superuser_content.xml --authors=create --quiet --allow-root

- name: Regenerate thumbnails for the imported posts
  shell: >
    sudo -u www-data wp --path=/var/www/html media regenerate --yes --quiet

- name: Trigger post-activation hooks
  shell: >
    sudo -u www-data wp --path=/var/www/html
    cron test

- name: Flush rewrite rules, setup htaccess for nice permalinks
  shell: >
    sudo -u www-data
    WP_CLI_CONFIG_PATH=/var/www/html/wp-content/themes/superuser/wp-cli.yml
    wp --path=/var/www/html
    rewrite flush --hard
