---
horizon_url: "https://salesdemo-sjc.openstack.blueboxgrid.com"

auth: {
  auth_url: "https://salesdemo-sjc.openstack.blueboxgrid.com:5000/v2.0",
  username: "litong01",
  password: "{{ password }}",
  project_name: "Interop"
}

app_env: {
  target_os: "ubuntu",
  ssh_user: "ubuntu",
  image_name: "ubuntu-16.10",
  region_name: "",
  availability_zone: "",
  validate_certs: True,
  private_net_name: "interopnet",
  flavor_name: "m1.small",
  public_key_file: "/home/ubuntu/.ssh/id_rsa.pub",
  stack_size: 4,
  volume_size: 10,
  block_device_name: "/dev/vdb",
  wp_latest: "https://wordpress.org/wordpress-4.6.1.tar.gz",
  wp_importer: "http://downloads.wordpress.org/plugin/wordpress-importer.0.6.3.zip"
}
